#计算机连接8串口分配器的USB端口
com: 
    usbport: COM5

#8串口分配器的参数配置

#8串口分配器的起始指令
uart8: 
      start: 1B43DD0D0A
#给8路串口分配器发送指令的波特率
      baudrate: 38400

#8串口分配器的分配COM通道
      com1 : 01
      com2 : 02
      com3 : 03
      com4 : 04
      com5 : 05
      com6 : 06
      com7 : 07
      com8 : 08
 
#校验方式
#无校验
      uncheck : 00
#奇校验
      evencheck : 01
#偶校验
      oddcheck : 02

#8串口分配器的分配COM通道通信需要使用的波特率
      300 : 00
      600 : 01
      1200 : 02
      2400 : 03
      4800 : 04
      9600 : 05
      14400 : 06
      19200 : 07
      38400 : 08
      57600 : 09
      
#投影机的参数配置
#optoma型号通用的投影机串口命令
optoma: 
       open : 7E3030303020310D
       close : 7E3030303020300D
       
       
       
       

     
      
      
      
      