server: 
       port: 8081
       servlet-path: /
  
logging: 
        config: classpath:logback.xml
        path: D:/spring-boot/logs
# ================================================
#                   Thymeleaf配置
# ================================================
# 是否启用thymeleaf模板解析
spring:
       thymeleaf: 
                 enabled: true
# 是否开启模板缓存（建议：开发环境下设置为false，生产环境设置为true）
                 cache: false
# Check that the templates location exists.
                 check-template-location: true
# 模板的媒体类型设置，默认为text/html
                 content-type: text/html
# 模板的编码设置，默认UTF-8
                 encoding: UTF-8
# 设置可以被解析的视图，以逗号,分隔
#spring.thymeleaf.view-names=
# 排除不需要被解析视图，以逗号,分隔
#spring.thymeleaf.excluded-view-names=
# 模板模式设置，默认为HTML5
#spring.thymeleaf.mode=HTML5
# 前缀设置，SpringBoot默认模板放置在classpath:/template/目录下
                 prefix: classpath:/templates/
# 后缀设置，默认为.html
                 suffix: .html
# 模板在模板链中被解析的顺序
#spring.thymeleaf.template-resolver-order=
